In [1]:
import numpy as np

In [2]:
from kaggle_environments import make
from kaggle_environments.envs.halite.helpers import *

# Create a test environment for use later
board_size = 5
environment = make("halite", configuration={"size": board_size, "startingHalite": 1000})
agent_count = 4
environment.reset(agent_count)
state = environment.state[0]
board = Board(state.observation, environment.configuration)

In [3]:
ships=[ship.position for ship in board.ships.values()]
owner=[ship.player_id+1 for ship in board.ships.values()]#plus 1 to begin with player 1 not 0
shipyards=[shipyard.position for shipyard in board.shipyards.values()]
owner2=[shipyard.player_id+1 for shipyard in board.shipyards.values()]#plus 1 to begin with player 1 not 0
halite=[cell.halite/500 for cell in board.cells.values()]#scale 0-1 1 being max halite=500

In [4]:
encode=np.zeros((3,board_size,board_size))
for i in range(0,len(ships)):
    encode[0,ships[i][0],ships[i][1]]=owner[i]
for i in range(0,len(shipyards)):
    encode[1,shipyards[i][0],shipyards[i][1]]=owner2[i]
encode[2]=np.array(halite).reshape(board_size,board_size).T #Halite list reshaped into array


In [5]:
#View output

print(board)

print(encode[0])
print(encode[1])
print(encode[2])

| 0 | 3 | 0 | 3 | 0 |
| 0 |a0 | 0 |b0 | 0 |
| 0 | 0 | 0 | 0 | 0 |
| 0 |c0 | 0 |d0 | 0 |
| 0 | 3 | 0 | 3 | 0 |

[[0. 0. 0. 0. 0.]
 [0. 3. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 4. 0. 2. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0.042 0.39  0.054 0.39  0.042]
 [0.    0.    0.    0.    0.   ]
 [0.    0.004 0.004 0.004 0.   ]
 [0.    0.    0.    0.    0.   ]
 [0.042 0.39  0.054 0.39  0.042]]


In [14]:
round(3.5)

4

In [19]:
'abc'<'i'

True

In [20]:
os._exit(0)

NameError: name 'os' is not defined